Come hang out with Bryan Liles as he does a bit of hands on hacking of Kubernetes and related topics. Some of this will be Bryan talking about the things he knows. Some of this will be Bryan exploring something new with the audience. Come join the fun

TODO: I want to make this document interactive version of the video, I am asking for help incorporating the go code and k8s commands into this document so people who watch the video can interactively play along with the power of org w

https://www.youtube.com/watch?v=ezM2H-tHMXk

Goal: Show a few k8s technologies in one video.

* News
 - https://github.com/vmware-tanzu/tgik/tree/master/episodes/115#community :)
 - quick shout out to the comunity
 - HELM 3.2.0 is graduating!!
 - Paris pitman has her 100th podcast outside                                       
 - K8s contributors better communications with a new team (https://kubernetes.io/blog/2020/04/21/contributor-communication/)
 - Contour is getting donated (ingress tool)


* Lets deploy an application on k8s
 - This is the go app, a simple cow say app,  git@github.com:bryanl/websay.git 
 - Go create a docker file. (walks through a simple docker file with scratch as base image).
 - Discuss using "Distroless" images in our docker files https://github.com/GoogleContainerTools/distroless
 - Talk about cloudNative build packs to help with docker files, you can use pack instead of Dockerfile https://buildpacks.io/
 - Deletes earlier docker file and creates image that will end up deployed to k8s just using "pack"
 - Talk about minikube vs kind. Says minikube is his preference
   
* Create deployment
 - Copy example from https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
 - Or create it with:
 #+begin_src bash
   kubectl create deployment [NAME]
 #+end_src
 #+RESULTS:


We are on 34 minutes 
