#+TITLE: VIM Commands Summary

* Introduction

This tips is for using the VIM mode of Spacemacs.

Insertion mode, type i or a to insert after the cursor.
To get back into normal mode, press the Esc key or rapidly press f d.
Pressing <ESC> will place you in normal state or will cancel an unwanted and partially completed command.
This commands are executed in command mode / normal state.

 The format for a command in Command Mode (normal state) is:
- [number]  command  object    OR    command  [number]  object where:
- number - is how many times to repeat the command
- command - is what to do, such as  d  for delete
- object - is what the command should act upon, such as  w  for word.

* Editor
Switch on menu bar: Spc Spc Type: Menu and select Menu-bar-mode
Quit   SPACE q q
Increase/decrease font size   SPACE z x (+ k, k, etc. -j, j etc.)

To see all open buffers Type Spc bb
Cancel incomplte / wrong command type: Clt G

Note: Combinations of refering to text object using:
w for word
S for sentence
p for paragraph
. repeat the last command

* Files
Open a file   SPACE f f   (then ctrl h to go up a directory, TAB for completion)
Save a file   SPACE f s
Create a file   SPACE f f <type in the new file path, press enter, it will ask to create a file>
Find a file in your project   SPACE p f
Edit the .spacemacs config file   SPACE f e d
Switch to a file recently opened   SPACE b b
 :w FILENAME  writes the current buffer to disk with file name FILENAME.
 :#,#w FILENAME  saves the lines # through # in file FILENAME.
 :r FILENAME  retrieves disk file FILENAME and inserts it into the current buffer following the cursor position.

* Find Text
Find text in buffer   /  (type search text, press ENTER, followed by n or N (next/previous))
Find next instance of a word that your cursor is over    *
Find previous instance of a word that your cursor is over    #
Turn off previous search highlighting   :nohl  (then press ENTER)
Find text in project   SPACE /
Find text under cursor in project (or selected with visual-mode)   SPACE *
Resume last search   SPACE s l
Find and replace text in buffer, from current line   :.,$s/<find text>/<replace text>/gc

* Navigation by "Finding"

Find in the line: 
- Type f<char>	find a character forward in a line and move to it
- Type t<char>	find a character forward in a line and move until it (one character before)
- Type F<char>	(f)ind a character backward in a line and move to it
- Type T<char>	find a character backward in a line and move until it
- ;	repeat last f, t, F, or T command
- To find other instances of a word, while on the word type: ** to hightlight all the same words and type n to go to the next word.

Note: Use f & t (or F&T) is combination with other commands to build a new command ie. dtx = delete till x or ytb = yank till b

* Navigation
Cursor is moved using either the arrow keys or the hjkl keys.
         h (left)        j (down)       k (up)            l (right)
H, M, L	move (H)igh, (M)iddle, or (L)ow within the view frame.
Move up a page   ctrl u
Move down a page   ctrl d
Move the line with cursor to the middle of the screen type: zz,
 - to the top type zt 
 - or bottom type: zb

Go up to next paragraph (whitepace line)   {
Go down to next paragraph (whitepace line)   }
Beginning of the line type: 0 (zero) or ^
End of the line type: $
Forward by word type: w (beginning of the word)
Forward by word type: e (end of the word)
Backwards by word type: b
  - number + w,e,b repeat the action by the number. ie. 7w move 7 words.

Add more lines between lines / Move lines down type: Ctrl j

Movement in the Buffer:
  - Type gg  to go to the beginning of a buffer.
  - Type  G  to move to the end of a buffer.
  - Go to line number type:    : number of the line you were on and then  <ENTER> .
  - Go to line number type: number G

Open / Collapse heading trees
  - Type: TAB for a single heading
  - Type: Spc TAB to cycle through all heading trees in the buffer.

Line numbers and movement related to line numners:
  - Move to a spesific line type:  : Line number
  - Activate relitive line numners Type: Spc t r. Change back to normal type Spc t n.

* Window (Frames) Layouts
Move between frames type Ctl x o (Small letter o)
Move between frames type Spc + frame number 
To close the active frame type Clt x 0 (zero) or Spc w c

Split frame vertically   SPACE w s
Split frame horizontally   SPACE w h
Resize windows Ctrl w + or -  of height and Ctrl w < or > for width  
Make all windows same size Ctrl w =
Navigate to the window in the given direction type <C-w>h,j,k,l - (<C-w>j navigates down)
Move the current window in the given direction Type <C-w>H,J,K,L - (<C-w>J moves it down)

* Buffers
To move between open Buffers (Files) type Spc + TAB

* Highlight Text with Visual Mode
Press v. (To enter visual mode so you can highlight text).
Use the arrow keys (or h,j,k,l,w,b,$) to highlight.
Type v i w for word selection, v i s for sentence selection

* Editing
- Type Formating (Bold, Underline etc.) Type , x + options in sub menu ie. b = Bold, u = Underline
- Make a title Type at the start of a line: #+TITLE This is a title
- Make a bullet point Type: * followed by the heading. Next level of bullet points type: ** and *** for the next level etc.
- Make a bullet point, 2nd options type: Alt + Enter + Enter
- To continue with bullet list, at the end of the previous line press Alt + Enter
- Add a TODO type Ctrl + shift and type Enter



** Copy, paste, Insert, Delete (Cut), Undo, Replace

  - To copy selected text type: y
  - Copy a word yw
  - Copy a line yy
  - Copy from cursor to end of line     y$ 
  - Copy & paste highlighted text from a register   Type "ay to yank into register a, and "ap to paste.
  - Show previous things you’ve copied (yanked)   SPACE r y
  - Copy highlighted text    Press y to yank, p to paste. (shift-p to open up a line above and paste)
  - To replace text that has already been deleted, type  p  this puts the deleted text AFTER the cursor (if a line was deleted it will go on the line below the cursor).

- Insert
  - To insert text at the cursor while in normal state type:   i - type in text
  - Typing  o  opens a line BELOW the cursor and places the cursor on the open line in insert state.
  - Typing a capital  O  opens the line ABOVE the line the cursor is on.
  - Type an  a  to insert text AFTER the character the cursor is on.
  - Typing a capital  A  automatically appends text to the end of the line.
  - Typing a capital  R  enters Replace mode until  <ESC>  is pressed to exit.

- Replace / Change
  - To replace the character under the cursor, type  r  and then the character which will replace the original.
  - Replace a word you are on type: C i W . It will delete the word and go to Inert mode
  - Replace a sentence you are on type: C i s . It will delete the sentence and go to Inert mode
  - The change command allows you to change the specified object from the cursor to the end of the object.  eg. Type  cw  to change from the cursor to the end of the word,  c$  to change to the end of a line. The format for change is:      [number]  c  object    OR    c  [number]  object 
  - Change everything between quotes   c i “    (this also works for parens, single quotes, etc.)

  - Substitue:
  - To substitute new for the first old on a line type  :s/old/new
  - To substitute new for all 'old's on a line type     :s/old/new/g
  - To substitute phrases between two line #'s type     :#,#s/old/new/g
  - To substitute all occurrences in the file type      :%s/old/new/g

- Delete: (Work as cut funtion)
  - Delete from the cursor to the end of a word type:  dw
  - Delete from the cursor to the end of a line type:  d$
  - Delete a whole line type:  dd
  - Delete complete line type: C  (Delete from cursor forward)
  - Delete a character under the cursor in normal state type:  x
  - Delete highlighted text   d
  - Delete word and insert text    cw
  - Delete to end of line     d$
  - Delete until right paren   df)
  - Delete a word you are on type: d a w
  - Delete a sentence you are on type: d a s
  - Delete to the end of the current word type: de
  - Delete to the end of next word type: d2e
  - Delete down a line (current and one below) type:	dj
  - Delete up until next closing parenthesis tpye: dt)
  - Delete up until the first search match for "world" type: d/world

- Undo / Redo
  - Undo entred command - Ctrl g
  - To undo previous actions, type:  u
  - To Redo (undo the undo's) type:  CTRL-Rc
  - To see Undo tree type: Spc a u
  - Redo   ctrl-r



* Executes an external command
- Type :!command  executes an external command.
  - Some useful examples are:
  -  :!ls  or  :!dir                 -  shows a directory listing.
  -  :!rm  or  :!del FILENAME        -  removes file FILENAME.

* Additional functions: 
Go to previous function[
Go to next function   ]]
Go up to outer brace   [{
Go down to outer brace   ]}
Comment out a line    g c c   (requires the evil-commentary layer)
Comment out highlighted text   g c
Indenting highlighted text    Type > or < to indent right or left.    (to indent more, type 2> or 3>)
Join lines separated by whitespace   J
Show whitespace   SPACE t w
Convert spaces to tabs   SPACE : (then type tabify and press ENTER)
Convert tabs to spaces   SPACE : (then type untabify and press ENTER)





